# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - node
before_script:
  - npm install -g gulp
script: gulp

# deploy to gh-pages: https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  local-dir: dist
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # set in the settings page of the repo on travis-ci.com
  keep-history: true
  on:
    branch: master
